@startuml

hide footbox
title DPP Flow (tokens)

actor Sender
actor Receiver
collections Indexer
participant Node

note over Sender: Sender wants to buy something from Receiver

autonumber
Sender-->Receiver: create basket of goods
Receiver->Receiver: create invoice (X satoshis, etc.)
Receiver->Receiver: display invoice [pay:url] \n(QR code or Bitcoin URI)

Receiver-->Sender: obtain payment protocol URL \n(scan QR code or click link)

group Direct Payment Procotol (DPP)
  Sender-[#red,bold]>Receiver: Request Payment Terms

  ' Receiver->Receiver: construct Payment Request arguments \n(destinations, fees, etc.)

  Receiver-[#red,bold]>Sender: Payment Terms

  Sender->Sender: Authorize? (click "OK")

  Sender-[#red,bold]>Receiver: Payment

  Receiver->Receiver: Validate Payment

  alt Invalid Tx

    Receiver->Sender: reject payment (error)

  else Valid Tx
    
    Receiver->Indexer ++: POST submitTransaction(Tx)
    Indexer->Indexer: Validate token tx
    Indexer->Node ++: POST submitTransaction(Tx)
    return transactionResponse
    return transactionResponse

    Receiver-[#red,bold]>Sender: Payment ACK

    ' mAPI->Receiver: Merkle Proof
    ' mAPI->Sender: Merkle Proof

  end

end
@enduml