definitions:
  bc.MapiCallback:
    properties:
      apiVersion:
        type: string
      blockHash:
        type: string
      blockHeight:
        type: integer
      callbackPayload:
        type: string
      callbackReason:
        type: string
      callbackTxId:
        type: string
      minerId:
        type: string
      timestamp:
        type: string
    type: object
  bc.MerkleProof:
    properties:
      composite:
        type: boolean
      index:
        type: integer
      nodes:
        items:
          type: string
        type: array
      proofType:
        type: string
      target:
        type: string
      targetType:
        type: string
      txOrId:
        type: string
    type: object
  bt.FeeQuote:
    type: object
  envelope.JSONEnvelope:
    properties:
      encoding:
        type: string
      mimetype:
        type: string
      payload:
        type: string
      publicKey:
        type: string
      signature:
        type: string
    type: object
  ibp.Merchant:
    properties:
      address:
        description: Address is the merchants store / head office address.
        example: 1 the street, the town, B1 1AA
        type: string
      avatar:
        description: AvatarURL displays a canonical url to a merchants avatar.
        example: http://url.com
        type: string
      email:
        description: Email can be sued to contact the merchant about this transaction.
        example: merchant@m.com
        type: string
      extendedData:
        additionalProperties: true
        description: ExtendedData can be supplied if the merchant wishes to send some
          arbitrary data back to the wallet.
        type: object
      name:
        description: Name is a human readable string identifying the merchant.
        example: merchant 1
        type: string
    type: object
  ibp.Output:
    properties:
      amount:
        description: Amount is the number of satoshis to be paid.
        example: 100000
        type: integer
      description:
        description: Description, an optional description such as "tip" or "sales
          tax". Maximum length is 100 chars.
        example: paymentReference 123456
        type: string
      script:
        description: Script is a locking script where payment should be sent, formatted
          as a hexadecimal string.
        example: 76a91455b61be43392125d127f1780fb038437cd67ef9c88ac
        type: string
    type: object
  ibp.Payment:
    properties:
      memo:
        description: Memo is a plain-text note from the customer to the payment host.
        example: for invoice 123456
        type: string
      merchantData:
        $ref: '#/definitions/ibp.Merchant'
        description: |-
          MerchantData is copied from PaymentDetails.merchantData.
          Payment hosts may use invoice numbers or any other data they require to match Payments to PaymentRequests.
          Note that malicious clients may modify the merchantData, so should be authenticated
          in some way (for example, signed with a payment host-only key).
          Maximum length is 10000 characters.
      rawTx:
        description: RawTX should be sent if SPVRequired is set to false in the payment
          request.
        type: string
      refundTo:
        description: |-
          RefundTo is a paymail to send a refund to should a refund be necessary.
          Maximum length is 100 characters
        example: me@paymail.com
        type: string
      ancestors:
        $ref: '#/definitions/bc.ancestors'
        description: |-
          TxAncestors which contains the details of previous transaction and Merkle proof of each input UTXO.
          Should be available if SPVRequired is set to true in the paymentRequest.
          See https://tsc.bitcoinassociation.net/standards/transaction-ancestors/
    type: object
  ibp.PaymentACK:
    properties:
      txid: 
        type: string
        description: Transaction ID
      rawtx: 
        type: string
        # nullable: true
        description: String of raw transaction bytes in hexadecimal format
      error:
        description: |-
          A number indicating why the transaction was not accepted. 0 or undefined indicates no error.
          A 1 or any other positive integer indicates an error. The errors are left undefined for now;
          it is recommended only to use “1” and to fill the memo with a textual explanation about why
          the transaction was not accepted until further numbers are defined and standardised.
        type: integer
      memo:
        type: string
    type: object
  ibp.PaymentDestinations:
    properties:
      outputs:
        items:
          $ref: '#/definitions/ibp.Output'
        type: array
    type: object
  ibp.PaymentRequest:
    properties:
      creationTimestamp:
        description: |-
          CreationTimestamp Unix timestamp (seconds since 1-Jan-1970 UTC) when the PaymentRequest was created.
          Required.
        example: "2019-10-12T07:20:50.52Z"
        type: string
      destinations:
        $ref: '#/definitions/ibp.PaymentDestinations'
        description: |-
          Destinations contains supported payment destinations by the merchant and ibp server, initial P2PKH outputs but can be extended.
          Required.
      expirationTimestamp:
        description: |-
          ExpirationTimestamp Unix timestamp (UTC) after which the PaymentRequest should be considered invalid.
          Optional.
        example: "2019-10-12T07:20:50.52Z"
        type: string
      fees:
        $ref: '#/definitions/bt.FeeQuote'
        description: |-
          FeeRate defines the amount of fees a users wallet should add to the payment
          when submitting their final payments.
      memo:
        description: |-
          Memo Optional note that should be displayed to the customer, explaining what this PaymentRequest is for.
          Maximum length is 50 characters.
        example: invoice number 123456
        type: string
      merchantData:
        $ref: '#/definitions/ibp.Merchant'
        description: |-
          MerchantData contains arbitrary data that may be used by the payment host to identify the PaymentRequest.
          May be omitted if the payment host does not need to associate Payments with PaymentRequest
          or if they associate each PaymentRequest with a separate payment address.
          Maximum length is 10000 characters.
      network:
        description: |-
          Network  Always set to "bitcoin" (but seems to be set to 'bitcoin-sv'
          outside bip270 spec, see https://handcash.github.io/handcash-merchant-integration/#/merchant-payments)
          {enum: bitcoin, bitcoin-sv, test}
          Required.
        enum:
        - mainnet
        - testnet
        - stn
        - regtest
        example: mainnet
        type: string
      paymentUrl:
        description: |-
          PaymentURL secure HTTPS location where a Payment message (see below) will be sent to obtain a PaymentACK.
          Maximum length is 4000 characters
        example: https://localhost:3443/api/v1/payment/123456
        type: string
      spvRequired:
        description: |-
          SPVRequired if true will expect the sender to submit an TxAncestors in the payment request, otherwise
          a rawTx will be required.
        example: true
        type: boolean
    type: object
  server.ClientError:
    properties:
      code:
        example: N01
        type: string
      id:
        example: e97970bf-2a88-4bc8-90e6-2f597a80b93d
        type: string
      message:
        example: unable to find foo when loading bar
        type: string
      title:
        example: not found
        type: string
    type: object
  bc.ancestors:
    properties:
      mapiResponses:
        items:
          $ref: '#/definitions/bc.MapiCallback'
        type: array
      parents:
        additionalProperties:
          $ref: '#/definitions/bc.ancestors'
        type: object
      proof:
        $ref: '#/definitions/bc.MerkleProof'
      rawTx:
        type: string
      txid:
        type: string
    type: object
host: localhost:8445
info:
  contact: {}
  description: A protocol for communication between a payment host (usually either a merchant, a payment processor, or simply the recipient's wallet) and their customer (the sender of the funds), enabling both a better customer experience, simpler wallet infrastructure, more advanced features such as multiple outputs, and better security against man-in-the-middle attacks on the payment process.
  license:
    name: ISC
    url: https://tsc.bitcoinassociation.net/standards/invoice_based_payments/
  # termsOfService: 
  title: Invoice Based Payments (IBP)
  version: 0.0.1
paths:
  /api/v1/payment/{paymentID}:
    get:
      consumes:
      - application/json
      description: Requests an invoice specified by the payment/invoice id (the identifier
        for an invoice).
      parameters:
      - description: Payment ID
        in: path
        name: paymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: contains outputs, merchant data and expiry information, used
            by the payee to construct a transaction
          schema:
            $ref: '#/definitions/ibp.PaymentRequest'
        "400":
          description: returned if the user input is invalid, usually an issue with
            the paymentID
          schema:
            $ref: '#/definitions/server.ClientError'
        "404":
          description: returned if the paymentID has not been found
          schema:
            $ref: '#/definitions/server.ClientError'
        "500":
          description: returned if there is an unexpected internal error
          schema:
            type: string
      summary: Request to pay an invoice and receive back outputs to use when constructing
        the payment transaction
      tags:
      - Invoice
    post:
      consumes:
      - application/json
      description: Creates a payment based on a payment id (the identifier for an
        invoice).
      parameters:
      - description: Payment ID
        in: path
        name: paymentID
        required: true
        type: string
      - description: payment message used in BIP270
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ibp.Payment'
      produces:
      - application/json
      responses:
        "201":
          description: if success, error code will be empty, otherwise it will be
            filled in with reason
          schema:
            $ref: '#/definitions/ibp.PaymentACK'
        "400":
          description: returned if the user input is invalid, usually an issue with
            the paymentID
          schema:
            $ref: '#/definitions/server.ClientError'
        "404":
          description: returned if the paymentID has not been found
          schema:
            $ref: '#/definitions/server.ClientError'
        "500":
          description: returned if there is an unexpected internal error
          schema:
            type: string
      summary: A user will submit an SpvEnvelope along with other information that
        is validated before being broadcast to the network.
      tags:
      - Payment
swagger: "2.0"
